### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by szorowi1** [ndawlab/mars-irt#3]
## Coding / Analysis
- [x] fix sgddm
- [x] fix variance explained
- [x] LOO in deviance scale
- [x] Rasch model table

## Repository
- [x] Documentation
- [x] Organization / README
- [x] Transfer to Daw lab

## Manuscript
- [x] Incorporate edits
- [x] finalize tables / figures
